// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace demoCodedUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// GoToSummerDress
        /// </summary>
        public void GoToSummerDress()
        {
            #region Variable Declarations
            HtmlHyperlink uIWomenHyperlink = this.UIFacebookloginorsignuWindow.UIDressesMyStoreDocument.UIBlock_top_menuPane.UIWomenHyperlink;
            HtmlCustom uIItemCustom = this.UIFacebookloginorsignuWindow.UIDressesMyStoreDocument.UIBlock_top_menuPane.UIItemCustom;
            HtmlHyperlink uIEveningDressesHyperlink = this.UIFacebookloginorsignuWindow.UIDressesMyStoreDocument.UIBlock_top_menuPane.UIEveningDressesHyperlink;
            HtmlHyperlink uISummerDressesHyperlink = this.UIFacebookloginorsignuWindow.UIDressesMyStoreDocument.UIBlock_top_menuPane.UISummerDressesHyperlink;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Women' link at (1, 1)
            Mouse.Hover(uIWomenHyperlink, new Point(1, 1));

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom, new Point(1, 1));

            // Mouse hover 'Evening Dresses' link at (1, 1)
            Mouse.Hover(uIEveningDressesHyperlink, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Summer Dresses' link
            Mouse.Click(uISummerDressesHyperlink, new Point(50, 3));
        }
        
        /// <summary>
        /// GoToDressesSummerDresses
        /// </summary>
        public void GoToDressesSummerDresses()
        {
            #region Variable Declarations
            HtmlImage uIModulesthemeconfigurImage = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIHtmlcontent_topPane.UIModulesthemeconfigurImage;
            HtmlImage uISample2Image = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIHomesliderCustom.UISample2Image;
            HtmlImage uISample3Image = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIHomesliderCustom.UISample3Image;
            HtmlDiv uIEXCEPTEUROCCAECATLorPane = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIHomesliderCustom.UIEXCEPTEUROCCAECATLorPane;
            HtmlHyperlink uIDressesHyperlink = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIBlock_top_menuPane.UIDressesHyperlink;
            HtmlHyperlink uITshirtsHyperlink = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIBlock_top_menuPane.UITshirtsHyperlink;
            HtmlHyperlink uIEveningDressesHyperlink = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIBlock_top_menuPane.UIEveningDressesHyperlink;
            HtmlCustom uIItemCustom = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIBlock_top_menuPane.UIItemCustom;
            HtmlHyperlink uISummerDressesHyperlink = this.UIMyStoreInternetExploWindow.UIMyStoreDocument.UIBlock_top_menuPane.UISummerDressesHyperlink;
            #endregion

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/modules/themeconfigurator/img/banner-img7.jpg' image at (1, 1)
            Mouse.Hover(uIModulesthemeconfigurImage, new Point(1, 1));

            // Mouse hover 'sample-2' image at (1, 1)
            Mouse.Hover(uISample2Image, new Point(1, 1));

            // Mouse hover 'sample-3' image at (1, 1)
            Mouse.Hover(uISample3Image, new Point(1, 1));

            // Mouse hover 'EXCEPTEUR OCCAECAT Lorem ipsum dolor' pane at (1, 1)
            Mouse.Hover(uIEXCEPTEUROCCAECATLorPane, new Point(1, 1));

            // Mouse hover 'Dresses' link at (1, 1)
            Mouse.Hover(uIDressesHyperlink, new Point(1, 1));

            // Mouse hover 'T-shirts' link at (1, 1)
            Mouse.Hover(uITshirtsHyperlink, new Point(1, 1));

            // Mouse hover 'Evening Dresses' link at (1, 1)
            Mouse.Hover(uIEveningDressesHyperlink, new Point(1, 1));

            // Mouse hover  custom control at (1, 1)
            Mouse.Hover(uIItemCustom, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Summer Dresses' link
            Mouse.Click(uISummerDressesHyperlink, new Point(58, 5));
        }
        
        /// <summary>
        /// opennewproject
        /// </summary>
        public void opennewproject()
        {
            #region Variable Declarations
            WpfMenuItem uIFileMenuItem = this.UIStartPageMicrosoftViWindow.UIMenuBarMenuBar.UIFileMenuItem;
            WpfMenuItem uIProjectMenuItem = this.UIStartPageMicrosoftViWindow.UIMenuBarMenuBar.UIFileMenuItem.UINewMenuItem.UIProjectMenuItem;
            #endregion

            // Click 'File' menu item
            Mouse.Click(uIFileMenuItem, new Point(24, 16));

            // Click 'File' -> 'New' -> 'Project...' menu item
            Mouse.Click(uIProjectMenuItem, new Point(51, 5));
        }
        
        /// <summary>
        /// SelecttheProject - Use 'SelecttheProjectParams' to pass parameters into this method.
        /// </summary>
        public void SelecttheProject()
        {
            #region Variable Declarations
            WpfExpander uIItemExpander = this.UINewProjectWindow.UIM_vsExtnsExplorerCtlCustom.UIExtensionProvidersLiTable.UIInstalledDataItem.UIItemCell.UIItemExpander;
            WpfTreeItem uIVisualCTreeItem = this.UINewProjectWindow.UIItemExpander.UIInstalledTree.UITemplatesTreeItem.UIVisualCTreeItem;
            #endregion

            // Expand expander
            uIItemExpander.Expanded = this.SelecttheProjectParams.UIItemExpanderExpanded;

            // Click 'Templates' -> 'Visual C#' tree item
            Mouse.Click(uIVisualCTreeItem, new Point(35, 15));

            // Last mouse action was not recorded.
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfRadioButton uITCMRadioButtonRadioButton = this.UIGenerateCodeforCodedWindow.UIElementHost1Window.UIElementHost1Client.UIElementHost1Pane.UITestCreationOptionDiCustom.UITCMRadioButtonRadioButton;
            #endregion

            // Select 'TCMRadioButton' radio button
            uITCMRadioButtonRadioButton.Selected = this.RecordedMethod1Params.UITCMRadioButtonRadioButtonSelected;
        }
        
        /// <summary>
        /// RecordedMethod2
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfButton uICancelButton = this.UIGenerateCodeforCodedWindow.UIElementHost1Window.UIElementHost1Client.UIElementHost1Pane.UITestCreationOptionDiCustom.UICancelButton;
            #endregion

            // Click 'Cancel' button
            Mouse.Click(uICancelButton, new Point(60, 20));
        }
        
        /// <summary>
        /// RecordedMethod3
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            WpfButton uITestExplorerButton = this.UICodedUITestProject6MWindow.UITestExplorerButton;
            #endregion

            // Click 'Test Explorer' button
            Mouse.Click(uITestExplorerButton, new Point(25, 55));
        }
        
        /// <summary>
        /// RecordedMethod4 - Use 'RecordedMethod4Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations
            WpfEdit uISearchEdit = this.UICodedUITestProject6MWindow.UISearchControlCustom.UISearchEdit;
            #endregion

            // Type 'abc' in 'Search' text box
            uISearchEdit.Text = this.RecordedMethod4Params.UISearchEditText;
        }
        
        #region Properties
        public virtual SelecttheProjectParams SelecttheProjectParams
        {
            get
            {
                if ((this.mSelecttheProjectParams == null))
                {
                    this.mSelecttheProjectParams = new SelecttheProjectParams();
                }
                return this.mSelecttheProjectParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual RecordedMethod4Params RecordedMethod4Params
        {
            get
            {
                if ((this.mRecordedMethod4Params == null))
                {
                    this.mRecordedMethod4Params = new RecordedMethod4Params();
                }
                return this.mRecordedMethod4Params;
            }
        }
        
        public UIFacebookloginorsignuWindow UIFacebookloginorsignuWindow
        {
            get
            {
                if ((this.mUIFacebookloginorsignuWindow == null))
                {
                    this.mUIFacebookloginorsignuWindow = new UIFacebookloginorsignuWindow();
                }
                return this.mUIFacebookloginorsignuWindow;
            }
        }
        
        public UIMyStoreInternetExploWindow UIMyStoreInternetExploWindow
        {
            get
            {
                if ((this.mUIMyStoreInternetExploWindow == null))
                {
                    this.mUIMyStoreInternetExploWindow = new UIMyStoreInternetExploWindow();
                }
                return this.mUIMyStoreInternetExploWindow;
            }
        }
        
        public UIStartPageMicrosoftViWindow UIStartPageMicrosoftViWindow
        {
            get
            {
                if ((this.mUIStartPageMicrosoftViWindow == null))
                {
                    this.mUIStartPageMicrosoftViWindow = new UIStartPageMicrosoftViWindow();
                }
                return this.mUIStartPageMicrosoftViWindow;
            }
        }
        
        public UINewProjectWindow UINewProjectWindow
        {
            get
            {
                if ((this.mUINewProjectWindow == null))
                {
                    this.mUINewProjectWindow = new UINewProjectWindow();
                }
                return this.mUINewProjectWindow;
            }
        }
        
        public UIGenerateCodeforCodedWindow UIGenerateCodeforCodedWindow
        {
            get
            {
                if ((this.mUIGenerateCodeforCodedWindow == null))
                {
                    this.mUIGenerateCodeforCodedWindow = new UIGenerateCodeforCodedWindow();
                }
                return this.mUIGenerateCodeforCodedWindow;
            }
        }
        
        public UICodedUITestProject6MWindow UICodedUITestProject6MWindow
        {
            get
            {
                if ((this.mUICodedUITestProject6MWindow == null))
                {
                    this.mUICodedUITestProject6MWindow = new UICodedUITestProject6MWindow();
                }
                return this.mUICodedUITestProject6MWindow;
            }
        }
        #endregion
        
        #region Fields
        private SelecttheProjectParams mSelecttheProjectParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private RecordedMethod4Params mRecordedMethod4Params;
        
        private UIFacebookloginorsignuWindow mUIFacebookloginorsignuWindow;
        
        private UIMyStoreInternetExploWindow mUIMyStoreInternetExploWindow;
        
        private UIStartPageMicrosoftViWindow mUIStartPageMicrosoftViWindow;
        
        private UINewProjectWindow mUINewProjectWindow;
        
        private UIGenerateCodeforCodedWindow mUIGenerateCodeforCodedWindow;
        
        private UICodedUITestProject6MWindow mUICodedUITestProject6MWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SelecttheProject'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SelecttheProjectParams
    {
        
        #region Fields
        /// <summary>
        /// Expand expander
        /// </summary>
        public bool UIItemExpanderExpanded = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'TCMRadioButton' radio button
        /// </summary>
        public bool UITCMRadioButtonRadioButtonSelected = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod4'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod4Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'abc' in 'Search' text box
        /// </summary>
        public string UISearchEditText = "abc";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFacebookloginorsignuWindow : BrowserWindow
    {
        
        public UIFacebookloginorsignuWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Facebook – log in or sign up";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Facebook – log in or sign up");
            this.WindowTitles.Add("Dresses - My Store");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIDressesMyStoreDocument UIDressesMyStoreDocument
        {
            get
            {
                if ((this.mUIDressesMyStoreDocument == null))
                {
                    this.mUIDressesMyStoreDocument = new UIDressesMyStoreDocument(this);
                }
                return this.mUIDressesMyStoreDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIDressesMyStoreDocument mUIDressesMyStoreDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDressesMyStoreDocument : HtmlDocument
    {
        
        public UIDressesMyStoreDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "category";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Dresses - My Store";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/index.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://automationpractice.com/index.php?id_category=8&controller=category";
            this.WindowTitles.Add("Dresses - My Store");
            #endregion
        }
        
        #region Properties
        public UIBlock_top_menuPane UIBlock_top_menuPane
        {
            get
            {
                if ((this.mUIBlock_top_menuPane == null))
                {
                    this.mUIBlock_top_menuPane = new UIBlock_top_menuPane(this);
                }
                return this.mUIBlock_top_menuPane;
            }
        }
        #endregion
        
        #region Fields
        private UIBlock_top_menuPane mUIBlock_top_menuPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBlock_top_menuPane : HtmlDiv
    {
        
        public UIBlock_top_menuPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "block_top_menu";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Categories\r\n\r\nWomen\r\nTopsT-shirts\r\nBlous";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "sf-contener clearfix col-lg-12";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sf-contener clearfix col-lg-12\" id=\"block_top_menu\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "38";
            this.WindowTitles.Add("Dresses - My Store");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDressesHyperlink
        {
            get
            {
                if ((this.mUIDressesHyperlink == null))
                {
                    this.mUIDressesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Dresses";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Dresses";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=8&controller=category";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "sf-with-ul";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Dresses\" class=\"sf-with-ul\" href=";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "9";
                    this.mUIDressesHyperlink.WindowTitles.Add("Dresses - My Store");
                    #endregion
                }
                return this.mUIDressesHyperlink;
            }
        }
        
        public HtmlHyperlink UIWomenHyperlink
        {
            get
            {
                if ((this.mUIWomenHyperlink == null))
                {
                    this.mUIWomenHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIWomenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIWomenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIWomenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIWomenHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Women";
                    this.mUIWomenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUIWomenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Women";
                    this.mUIWomenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=3&controller=category";
                    this.mUIWomenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "sf-with-ul";
                    this.mUIWomenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Women\" class=\"sf-with-ul\" href=\"h";
                    this.mUIWomenHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIWomenHyperlink.WindowTitles.Add("Dresses - My Store");
                    #endregion
                }
                return this.mUIWomenHyperlink;
            }
        }
        
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "UL";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "submenu-container clearfix first-in-line-xs";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"submenu-container clearfix first-";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "2";
                    this.mUIItemCustom.WindowTitles.Add("Dresses - My Store");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlHyperlink UIEveningDressesHyperlink
        {
            get
            {
                if ((this.mUIEveningDressesHyperlink == null))
                {
                    this.mUIEveningDressesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evening Dresses";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Evening Dresses";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=10&controller=category";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Evening Dresses\" href=\"http://aut";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIEveningDressesHyperlink.WindowTitles.Add("Dresses - My Store");
                    #endregion
                }
                return this.mUIEveningDressesHyperlink;
            }
        }
        
        public HtmlHyperlink UISummerDressesHyperlink
        {
            get
            {
                if ((this.mUISummerDressesHyperlink == null))
                {
                    this.mUISummerDressesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Summer Dresses";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Summer Dresses";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=11&controller=category";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Summer Dresses\" href=\"http://auto";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mUISummerDressesHyperlink.WindowTitles.Add("Dresses - My Store");
                    #endregion
                }
                return this.mUISummerDressesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDressesHyperlink;
        
        private HtmlHyperlink mUIWomenHyperlink;
        
        private HtmlCustom mUIItemCustom;
        
        private HtmlHyperlink mUIEveningDressesHyperlink;
        
        private HtmlHyperlink mUISummerDressesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMyStoreInternetExploWindow : BrowserWindow
    {
        
        public UIMyStoreInternetExploWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "My Store";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("My Store");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMyStoreDocument UIMyStoreDocument
        {
            get
            {
                if ((this.mUIMyStoreDocument == null))
                {
                    this.mUIMyStoreDocument = new UIMyStoreDocument(this);
                }
                return this.mUIMyStoreDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMyStoreDocument mUIMyStoreDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMyStoreDocument : HtmlDocument
    {
        
        public UIMyStoreDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "index";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "My Store";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/index.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://automationpractice.com/index.php";
            this.WindowTitles.Add("My Store");
            #endregion
        }
        
        #region Properties
        public UIHtmlcontent_topPane UIHtmlcontent_topPane
        {
            get
            {
                if ((this.mUIHtmlcontent_topPane == null))
                {
                    this.mUIHtmlcontent_topPane = new UIHtmlcontent_topPane(this);
                }
                return this.mUIHtmlcontent_topPane;
            }
        }
        
        public UIHomesliderCustom UIHomesliderCustom
        {
            get
            {
                if ((this.mUIHomesliderCustom == null))
                {
                    this.mUIHomesliderCustom = new UIHomesliderCustom(this);
                }
                return this.mUIHomesliderCustom;
            }
        }
        
        public UIBlock_top_menuPane1 UIBlock_top_menuPane
        {
            get
            {
                if ((this.mUIBlock_top_menuPane == null))
                {
                    this.mUIBlock_top_menuPane = new UIBlock_top_menuPane1(this);
                }
                return this.mUIBlock_top_menuPane;
            }
        }
        #endregion
        
        #region Fields
        private UIHtmlcontent_topPane mUIHtmlcontent_topPane;
        
        private UIHomesliderCustom mUIHomesliderCustom;
        
        private UIBlock_top_menuPane1 mUIBlock_top_menuPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHtmlcontent_topPane : HtmlDiv
    {
        
        public UIHtmlcontent_topPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "htmlcontent_top";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"htmlcontent_top\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "56";
            this.WindowTitles.Add("My Store");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIModulesthemeconfigurImage
        {
            get
            {
                if ((this.mUIModulesthemeconfigurImage == null))
                {
                    this.mUIModulesthemeconfigurImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIModulesthemeconfigurImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIModulesthemeconfigurImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIModulesthemeconfigurImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIModulesthemeconfigurImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/modules/themeconfigurator/img/banner-img7.jpg";
                    this.mUIModulesthemeconfigurImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://automationpractice.com/modules/themeconfigurator/img/banner-img7.jpg";
                    this.mUIModulesthemeconfigurImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/";
                    this.mUIModulesthemeconfigurImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://www.prestashop.com/";
                    this.mUIModulesthemeconfigurImage.FilterProperties[HtmlImage.PropertyNames.Class] = "item-img";
                    this.mUIModulesthemeconfigurImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "width=\"381\" height=\"219\" title=\"\" class=";
                    this.mUIModulesthemeconfigurImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIModulesthemeconfigurImage.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUIModulesthemeconfigurImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIModulesthemeconfigurImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomesliderCustom : HtmlCustom
    {
        
        public UIHomesliderCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "homeslider";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"homeslider\" style=\"left: -1557.99px;";
            this.FilterProperties["TagInstance"] = "6";
            this.WindowTitles.Add("My Store");
            #endregion
        }
        
        #region Properties
        public HtmlImage UISample2Image
        {
            get
            {
                if ((this.mUISample2Image == null))
                {
                    this.mUISample2Image = new HtmlImage(this);
                    #region Search Criteria
                    this.mUISample2Image.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUISample2Image.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUISample2Image.SearchProperties[HtmlImage.PropertyNames.Alt] = "sample-2";
                    this.mUISample2Image.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/modules/homeslider/images/sample-2.jpg";
                    this.mUISample2Image.FilterProperties[HtmlImage.PropertyNames.Src] = "http://automationpractice.com/modules/homeslider/images/sample-2.jpg";
                    this.mUISample2Image.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/";
                    this.mUISample2Image.FilterProperties[HtmlImage.PropertyNames.Href] = "http://www.prestashop.com/?utm_source=v16_homeslider";
                    this.mUISample2Image.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUISample2Image.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "width=\"779\" height=\"448\" alt=\"sample-2\" ";
                    this.mUISample2Image.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "3";
                    this.mUISample2Image.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUISample2Image;
            }
        }
        
        public HtmlImage UISample3Image
        {
            get
            {
                if ((this.mUISample3Image == null))
                {
                    this.mUISample3Image = new HtmlImage(this);
                    #region Search Criteria
                    this.mUISample3Image.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUISample3Image.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUISample3Image.SearchProperties[HtmlImage.PropertyNames.Alt] = "sample-3";
                    this.mUISample3Image.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/modules/homeslider/images/sample-3.jpg";
                    this.mUISample3Image.FilterProperties[HtmlImage.PropertyNames.Src] = "http://automationpractice.com/modules/homeslider/images/sample-3.jpg";
                    this.mUISample3Image.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/";
                    this.mUISample3Image.FilterProperties[HtmlImage.PropertyNames.Href] = "http://www.prestashop.com/?utm_source=v16_homeslider";
                    this.mUISample3Image.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUISample3Image.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "width=\"779\" height=\"448\" alt=\"sample-3\" ";
                    this.mUISample3Image.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "4";
                    this.mUISample3Image.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUISample3Image;
            }
        }
        
        public HtmlDiv UIEXCEPTEUROCCAECATLorPane
        {
            get
            {
                if ((this.mUIEXCEPTEUROCCAECATLorPane == null))
                {
                    this.mUIEXCEPTEUROCCAECATLorPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIEXCEPTEUROCCAECATLorPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIEXCEPTEUROCCAECATLorPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIEXCEPTEUROCCAECATLorPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "EXCEPTEUR\r\nOCCAECAT\r\n\r\nLorem ipsum dolor";
                    this.mUIEXCEPTEUROCCAECATLorPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIEXCEPTEUROCCAECATLorPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "homeslider-description";
                    this.mUIEXCEPTEUROCCAECATLorPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"homeslider-description\"";
                    this.mUIEXCEPTEUROCCAECATLorPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "52";
                    this.mUIEXCEPTEUROCCAECATLorPane.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUIEXCEPTEUROCCAECATLorPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUISample2Image;
        
        private HtmlImage mUISample3Image;
        
        private HtmlDiv mUIEXCEPTEUROCCAECATLorPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBlock_top_menuPane1 : HtmlDiv
    {
        
        public UIBlock_top_menuPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "block_top_menu";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Categories\r\n\r\nWomen\r\nTopsT-shirts\r\nBlous";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "sf-contener clearfix col-lg-12";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"sf-contener clearfix col-lg-12\" id=\"block_top_menu\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "38";
            this.WindowTitles.Add("My Store");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDressesHyperlink
        {
            get
            {
                if ((this.mUIDressesHyperlink == null))
                {
                    this.mUIDressesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Dresses";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Dresses";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=8&controller=category";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "sf-with-ul";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Dresses\" class=\"sf-with-ul\" href=";
                    this.mUIDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "9";
                    this.mUIDressesHyperlink.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUIDressesHyperlink;
            }
        }
        
        public HtmlHyperlink UITshirtsHyperlink
        {
            get
            {
                if ((this.mUITshirtsHyperlink == null))
                {
                    this.mUITshirtsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITshirtsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITshirtsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITshirtsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITshirtsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "T-shirts";
                    this.mUITshirtsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUITshirtsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "T-shirts";
                    this.mUITshirtsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=5&controller=category";
                    this.mUITshirtsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUITshirtsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"T-shirts\" href=\"http://automation";
                    this.mUITshirtsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "13";
                    this.mUITshirtsHyperlink.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUITshirtsHyperlink;
            }
        }
        
        public HtmlHyperlink UIEveningDressesHyperlink
        {
            get
            {
                if ((this.mUIEveningDressesHyperlink == null))
                {
                    this.mUIEveningDressesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEveningDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Evening Dresses";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Evening Dresses";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=10&controller=category";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Evening Dresses\" href=\"http://aut";
                    this.mUIEveningDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "11";
                    this.mUIEveningDressesHyperlink.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUIEveningDressesHyperlink;
            }
        }
        
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "UL";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "submenu-container clearfix first-in-line-xs";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"submenu-container clearfix first-";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "5";
                    this.mUIItemCustom.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlHyperlink UISummerDressesHyperlink
        {
            get
            {
                if ((this.mUISummerDressesHyperlink == null))
                {
                    this.mUISummerDressesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISummerDressesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Summer Dresses";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/index.php";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Summer Dresses";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://automationpractice.com/index.php?id_category=11&controller=category";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Summer Dresses\" href=\"http://auto";
                    this.mUISummerDressesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "12";
                    this.mUISummerDressesHyperlink.WindowTitles.Add("My Store");
                    #endregion
                }
                return this.mUISummerDressesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDressesHyperlink;
        
        private HtmlHyperlink mUITshirtsHyperlink;
        
        private HtmlHyperlink mUIEveningDressesHyperlink;
        
        private HtmlCustom mUIItemCustom;
        
        private HtmlHyperlink mUISummerDressesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStartPageMicrosoftViWindow : WpfWindow
    {
        
        public UIStartPageMicrosoftViWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Start Page - Microsoft Visual Studio";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Start Page - Microsoft Visual Studio");
            #endregion
        }
        
        #region Properties
        public UIMenuBarMenuBar UIMenuBarMenuBar
        {
            get
            {
                if ((this.mUIMenuBarMenuBar == null))
                {
                    this.mUIMenuBarMenuBar = new UIMenuBarMenuBar(this);
                }
                return this.mUIMenuBarMenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIMenuBarMenuBar mUIMenuBarMenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMenuBarMenuBar : WpfControl
    {
        
        public UIMenuBarMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "MenuBar";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "MenuBar";
            this.WindowTitles.Add("Start Page - Microsoft Visual Studio");
            #endregion
        }
        
        #region Properties
        public UIFileMenuItem UIFileMenuItem
        {
            get
            {
                if ((this.mUIFileMenuItem == null))
                {
                    this.mUIFileMenuItem = new UIFileMenuItem(this);
                }
                return this.mUIFileMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIFileMenuItem mUIFileMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFileMenuItem : WpfMenuItem
    {
        
        public UIFileMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfMenuItem.PropertyNames.Name] = "File";
            this.WindowTitles.Add("Start Page - Microsoft Visual Studio");
            #endregion
        }
        
        #region Properties
        public UINewMenuItem UINewMenuItem
        {
            get
            {
                if ((this.mUINewMenuItem == null))
                {
                    this.mUINewMenuItem = new UINewMenuItem(this);
                }
                return this.mUINewMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UINewMenuItem mUINewMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewMenuItem : WpfMenuItem
    {
        
        public UINewMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfMenuItem.PropertyNames.Name] = "New";
            this.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
            this.WindowTitles.Add("Start Page - Microsoft Visual Studio");
            #endregion
        }
        
        #region Properties
        public WpfMenuItem UIProjectMenuItem
        {
            get
            {
                if ((this.mUIProjectMenuItem == null))
                {
                    this.mUIProjectMenuItem = new WpfMenuItem(this);
                    #region Search Criteria
                    this.mUIProjectMenuItem.SearchProperties[WpfMenuItem.PropertyNames.Name] = "Project...";
                    this.mUIProjectMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIProjectMenuItem.WindowTitles.Add("Start Page - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUIProjectMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfMenuItem mUIProjectMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewProjectWindow : WpfWindow
    {
        
        public UINewProjectWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "New Project";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public UIM_vsExtnsExplorerCtlCustom UIM_vsExtnsExplorerCtlCustom
        {
            get
            {
                if ((this.mUIM_vsExtnsExplorerCtlCustom == null))
                {
                    this.mUIM_vsExtnsExplorerCtlCustom = new UIM_vsExtnsExplorerCtlCustom(this);
                }
                return this.mUIM_vsExtnsExplorerCtlCustom;
            }
        }
        
        public UIItemExpander UIItemExpander
        {
            get
            {
                if ((this.mUIItemExpander == null))
                {
                    this.mUIItemExpander = new UIItemExpander(this);
                }
                return this.mUIItemExpander;
            }
        }
        #endregion
        
        #region Fields
        private UIM_vsExtnsExplorerCtlCustom mUIM_vsExtnsExplorerCtlCustom;
        
        private UIItemExpander mUIItemExpander;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIM_vsExtnsExplorerCtlCustom : WpfCustom
    {
        
        public UIM_vsExtnsExplorerCtlCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.VSExtensionsExplorerCtl";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "m_vsExtnsExplorerCtl";
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public UIExtensionProvidersLiTable UIExtensionProvidersLiTable
        {
            get
            {
                if ((this.mUIExtensionProvidersLiTable == null))
                {
                    this.mUIExtensionProvidersLiTable = new UIExtensionProvidersLiTable(this);
                }
                return this.mUIExtensionProvidersLiTable;
            }
        }
        #endregion
        
        #region Fields
        private UIExtensionProvidersLiTable mUIExtensionProvidersLiTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIExtensionProvidersLiTable : WpfTable
    {
        
        public UIExtensionProvidersLiTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "ProvidersUid";
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public UIInstalledDataItem UIInstalledDataItem
        {
            get
            {
                if ((this.mUIInstalledDataItem == null))
                {
                    this.mUIInstalledDataItem = new UIInstalledDataItem(this);
                }
                return this.mUIInstalledDataItem;
            }
        }
        #endregion
        
        #region Fields
        private UIInstalledDataItem mUIInstalledDataItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIInstalledDataItem : WpfControl
    {
        
        public UIInstalledDataItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "DataItem";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "Installed";
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public UIItemCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new UIItemCell(this);
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private UIItemCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCell : WpfCell
    {
        
        public UIItemCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Name";
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public WpfExpander UIItemExpander
        {
            get
            {
                if ((this.mUIItemExpander == null))
                {
                    this.mUIItemExpander = new WpfExpander(this);
                    #region Search Criteria
                    this.mUIItemExpander.WindowTitles.Add("New Project");
                    #endregion
                }
                return this.mUIItemExpander;
            }
        }
        #endregion
        
        #region Fields
        private WpfExpander mUIItemExpander;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemExpander : WpfExpander
    {
        
        public UIItemExpander(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public UIInstalledTree UIInstalledTree
        {
            get
            {
                if ((this.mUIInstalledTree == null))
                {
                    this.mUIInstalledTree = new UIInstalledTree(this);
                }
                return this.mUIInstalledTree;
            }
        }
        #endregion
        
        #region Fields
        private UIInstalledTree mUIInstalledTree;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIInstalledTree : WpfTree
    {
        
        public UIInstalledTree(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTree.PropertyNames.AutomationId] = "Installed";
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public UITemplatesTreeItem UITemplatesTreeItem
        {
            get
            {
                if ((this.mUITemplatesTreeItem == null))
                {
                    this.mUITemplatesTreeItem = new UITemplatesTreeItem(this);
                }
                return this.mUITemplatesTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UITemplatesTreeItem mUITemplatesTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITemplatesTreeItem : WpfTreeItem
    {
        
        public UITemplatesTreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTreeItem.PropertyNames.AutomationId] = "Templates";
            this.WindowTitles.Add("New Project");
            #endregion
        }
        
        #region Properties
        public WpfTreeItem UIVisualCTreeItem
        {
            get
            {
                if ((this.mUIVisualCTreeItem == null))
                {
                    this.mUIVisualCTreeItem = new WpfTreeItem(this);
                    #region Search Criteria
                    this.mUIVisualCTreeItem.SearchProperties[WpfTreeItem.PropertyNames.AutomationId] = "Visual C#";
                    this.mUIVisualCTreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIVisualCTreeItem.WindowTitles.Add("New Project");
                    #endregion
                }
                return this.mUIVisualCTreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfTreeItem mUIVisualCTreeItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIGenerateCodeforCodedWindow : WinWindow
    {
        
        public UIGenerateCodeforCodedWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Generate Code for Coded UI Test";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Generate Code for Coded UI Test");
            #endregion
        }
        
        #region Properties
        public UIElementHost1Window UIElementHost1Window
        {
            get
            {
                if ((this.mUIElementHost1Window == null))
                {
                    this.mUIElementHost1Window = new UIElementHost1Window(this);
                }
                return this.mUIElementHost1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIElementHost1Window mUIElementHost1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIElementHost1Window : WinWindow
    {
        
        public UIElementHost1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "elementHost1";
            this.WindowTitles.Add("Generate Code for Coded UI Test");
            #endregion
        }
        
        #region Properties
        public UIElementHost1Client UIElementHost1Client
        {
            get
            {
                if ((this.mUIElementHost1Client == null))
                {
                    this.mUIElementHost1Client = new UIElementHost1Client(this);
                }
                return this.mUIElementHost1Client;
            }
        }
        #endregion
        
        #region Fields
        private UIElementHost1Client mUIElementHost1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIElementHost1Client : WinClient
    {
        
        public UIElementHost1Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "elementHost1";
            this.WindowTitles.Add("Generate Code for Coded UI Test");
            #endregion
        }
        
        #region Properties
        public UIElementHost1Pane UIElementHost1Pane
        {
            get
            {
                if ((this.mUIElementHost1Pane == null))
                {
                    this.mUIElementHost1Pane = new UIElementHost1Pane(this);
                }
                return this.mUIElementHost1Pane;
            }
        }
        #endregion
        
        #region Fields
        private UIElementHost1Pane mUIElementHost1Pane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIElementHost1Pane : WpfPane
    {
        
        public UIElementHost1Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.Name] = "elementHost1";
            this.WindowTitles.Add("Generate Code for Coded UI Test");
            #endregion
        }
        
        #region Properties
        public UITestCreationOptionDiCustom UITestCreationOptionDiCustom
        {
            get
            {
                if ((this.mUITestCreationOptionDiCustom == null))
                {
                    this.mUITestCreationOptionDiCustom = new UITestCreationOptionDiCustom(this);
                }
                return this.mUITestCreationOptionDiCustom;
            }
        }
        #endregion
        
        #region Fields
        private UITestCreationOptionDiCustom mUITestCreationOptionDiCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITestCreationOptionDiCustom : WpfCustom
    {
        
        public UITestCreationOptionDiCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TestCreationOptionsDialog";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "TestCreationOptionDialogWindow";
            this.WindowTitles.Add("Generate Code for Coded UI Test");
            #endregion
        }
        
        #region Properties
        public WpfRadioButton UITCMRadioButtonRadioButton
        {
            get
            {
                if ((this.mUITCMRadioButtonRadioButton == null))
                {
                    this.mUITCMRadioButtonRadioButton = new WpfRadioButton(this);
                    #region Search Criteria
                    this.mUITCMRadioButtonRadioButton.SearchProperties[WpfRadioButton.PropertyNames.AutomationId] = "tcmRadioButton";
                    this.mUITCMRadioButtonRadioButton.WindowTitles.Add("Generate Code for Coded UI Test");
                    #endregion
                }
                return this.mUITCMRadioButtonRadioButton;
            }
        }
        
        public WpfButton UICancelButton
        {
            get
            {
                if ((this.mUICancelButton == null))
                {
                    this.mUICancelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICancelButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "CancelButton";
                    this.mUICancelButton.WindowTitles.Add("Generate Code for Coded UI Test");
                    #endregion
                }
                return this.mUICancelButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfRadioButton mUITCMRadioButtonRadioButton;
        
        private WpfButton mUICancelButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICodedUITestProject6MWindow : WpfWindow
    {
        
        public UICodedUITestProject6MWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CodedUITestProject6 - Microsoft Visual Studio";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CodedUITestProject6 - Microsoft Visual Studio");
            #endregion
        }
        
        #region Properties
        public WpfButton UITestExplorerButton
        {
            get
            {
                if ((this.mUITestExplorerButton == null))
                {
                    this.mUITestExplorerButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITestExplorerButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "AUTOHIDE_ST:0:0:{e1b7d1f8-9b3c-49b1-8f4f-bfc63a88835d}";
                    this.mUITestExplorerButton.WindowTitles.Add("CodedUITestProject6 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUITestExplorerButton;
            }
        }
        
        public UIPART_HwndHostPane UIPART_HwndHostPane
        {
            get
            {
                if ((this.mUIPART_HwndHostPane == null))
                {
                    this.mUIPART_HwndHostPane = new UIPART_HwndHostPane(this);
                }
                return this.mUIPART_HwndHostPane;
            }
        }
        
        public UISearchControlCustom UISearchControlCustom
        {
            get
            {
                if ((this.mUISearchControlCustom == null))
                {
                    this.mUISearchControlCustom = new UISearchControlCustom(this);
                }
                return this.mUISearchControlCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUITestExplorerButton;
        
        private UIPART_HwndHostPane mUIPART_HwndHostPane;
        
        private UISearchControlCustom mUISearchControlCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPART_HwndHostPane : WpfPane
    {
        
        public UIPART_HwndHostPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.AutoHideWindowContentControl";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "PART_HwndHost";
            this.WindowTitles.Add("CodedUITestProject6 - Microsoft Visual Studio");
            #endregion
        }
        
        #region Properties
        public WpfControl UIResizeGripIndicator
        {
            get
            {
                if ((this.mUIResizeGripIndicator == null))
                {
                    this.mUIResizeGripIndicator = new WpfControl(this);
                    #region Search Criteria
                    this.mUIResizeGripIndicator.SearchProperties[WpfControl.PropertyNames.ControlType] = "Indicator";
                    this.mUIResizeGripIndicator.SearchProperties[WpfControl.PropertyNames.AutomationId] = "ResizeGrip";
                    this.mUIResizeGripIndicator.WindowTitles.Add("CodedUITestProject6 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUIResizeGripIndicator;
            }
        }
        #endregion
        
        #region Fields
        private WpfControl mUIResizeGripIndicator;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISearchControlCustom : WpfCustom
    {
        
        public UISearchControlCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.SearchControl";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "SearchControl";
            this.WindowTitles.Add("CodedUITestProject6 - Microsoft Visual Studio");
            #endregion
        }
        
        #region Properties
        public WpfEdit UISearchEdit
        {
            get
            {
                if ((this.mUISearchEdit == null))
                {
                    this.mUISearchEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUISearchEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PART_SearchBox";
                    this.mUISearchEdit.WindowTitles.Add("CodedUITestProject6 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUISearchEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUISearchEdit;
        #endregion
    }
}
